<?php
global $lang, $app;
$app->loadLang('task');

$config->report->editor = new stdclass();
$config->report->editor->editscript   = array('id' => 'notice', 'tools' => 'simpleTools');

$config->report->search['module']                   = 'report';
$config->report->search['fields']['scriptName']     = $lang->task->scriptName;
$config->report->search['fields']['id']             = $lang->report->id;
$config->report->search['fields']['project']        = $lang->task->project;
//$config->report->search['fields']['storyTitle']   = $lang->task->story;
$config->report->search['fields']['openedBy']       = $lang->task->openedBy;
$config->report->search['fields']['finishedBy']     = $lang->task->finishedBy;
$config->report->search['fields']['finishedDate']   = $lang->task->finishedDate;
$config->report->search['fields']['scriptType']     = $lang->task->scriptType;
$config->report->search['fields']['lob']            = $lang->task->lob;
$config->report->search['fields']['frequency']      = $lang->task->frequency;
$config->report->search['fields']['performMode']    = $lang->task->performMode;
$config->report->search['fields']['performSystem']  = $lang->task->performSystem;
$config->report->search['fields']['scriptPath']     = $lang->task->scriptPath;
$config->report->search['fields']['releasedDate']   = $lang->task->releasedDate;
$config->report->search['fields']['tester']         = $lang->task->tester;
$config->report->search['fields']['AT']             = $lang->task->AT;
$config->report->search['fields']['released']       = $lang->task->released;
$config->report->search['fields']['configurationFile'] = $lang->task->configurationFile;
$config->report->search['fields']['output']         = $lang->task->output;
$config->report->search['fields']['precondition']   = $lang->task->precondition;
$config->report->search['fields']['performBody']    = $lang->task->performBody;
$config->report->search['fields']['notice']          = $lang->task->notice;

$config->report->search['params']['scriptName']     = array('operator' => 'include', 'control' => 'input',  'values' => '');
//$config->report->search['params']['storyTitle']   = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->report->search['params']['project']        = array('operator' => '=', 'control' => 'select', 'values' => 'projects');
$config->report->search['params']['openedBy']       = array('operator' => '=', 'control' => 'select', 'values' => 'users');
$config->report->search['params']['finishedBy']     = array('operator' => '=', 'control' => 'select', 'values' => 'users');
$config->report->search['params']['finishedDate']   = array('operator' => '=', 'control' => 'input',  'values' => '', 'class' => 'date');
$config->report->search['params']['scriptType']     = array('operator' => '=', 'control' => 'select',  'values' => $lang->task->scriptTypeList);
$config->report->search['params']['lob']            = array('operator' => '=', 'control' => 'select',  'values' => $lang->task->lobList);
$config->report->search['params']['frequency']      = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->report->search['params']['performMode']    = array('operator' => '=', 'control' => 'select',  'values' => $lang->task->performModeList);
$config->report->search['params']['performSystem']  = array('operator' => '=', 'control' => 'select',  'values' => $lang->task->performSystemList);
$config->report->search['params']['scriptPath']     = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->report->search['params']['releasedDate']   = array('operator' => '=', 'control' => 'input',  'values' => '', 'class' => 'date');
$config->report->search['params']['tester']         = array('operator' => '=', 'control' => 'select', 'values' => 'users');
$config->report->search['params']['AT']             = array('operator' => '=', 'control' => 'select',  'values' => $lang->task->ATList);
$config->report->search['params']['released']       = array('operator' => '=', 'control' => 'select',  'values' => $lang->task->releasedList);
$config->report->search['params']['configurationFile'] = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->report->search['params']['output']         = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->report->search['params']['precondition']   = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->report->search['params']['performBody']    = array('operator' => 'include', 'control' => 'input',  'values' => '');
$config->report->search['params']['notice']         = array('operator' => 'include', 'control' => 'input',  'values' => '');
